### ISSUE TITLE
TODO: Project Structure Overhaul

### ISSUE THREAD

**Issue by shengjiex98** [shengjiex98/skynet-plotting#5]
In (greatly) increasing difficulty:

- [x] Switch to node modules from CDN. Implicit dependency is BAD!
- [x] Use TypeScript.
  - [x] Setting TypeScript up
  - [x] Migrating some files to ts
  - [x] Migrating all files
- [ ] Use a modern framework.

**Comment by shengjiex98** [comment]
Good for now.
