### ISSUE TITLE
TODO: Upgrade Chart.js to version 3

### ISSUE THREAD

**Issue by shengjiex98** [shengjiex98/skynet-plotting#9]
**Major issues**
- [x] Disable animation (too slow if number of data points is large)
- [x] Fix handsontable resize error (kinda hackish, hopefully it's benign)
- [x] chart feels sluggish compared to before (use `update('none')` to disable animation)
- [x] Fix title and axes label not showing up for first chart.

**Minor optimization**
- [x] Default options include tooltip label callbacks
  - [x] Fix the issue that default tooltip callback overwrites specific callbacks for each mode.
- [x] Use Chart.defaults instead of setting it for each individual Chart object.
  - [x] Separate chart default options from automatic height update for tables.

**Comment by shengjiex98** [comment]
All clear
